containers:
  core:
    capAdd:
      - ALL
    disableInit: true
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    entrypoint: ["/lib/systemd/systemd"]
    hostIPC: true
    hostUTS: true
    hostNetwork: true
    image: skiffos/skiff-core-pinephone-neon:latest
    mounts:
      - /dev:/dev
      - /lib/modules:/lib/modules
      - /mnt/persist/core-docker:/var/lib/docker
      - /mnt:/mnt
      - /run/udev:/run/udev
    privileged: true
    restartPolicy: "always"
    securityOpt:
      - seccomp=unconfined
    startAfterCreate: true
    stopSignal: RTMIN+3
    tty: true
    workingDirectory: /home/core
users:
  core:
    container: core
    containerUser: core
    containerShell:
      - "/bin/bash"
    auth:
      copyRootKeys: true
images:
  skiffos/skiff-core-pinephone-neon:latest:
    build:
      source: /opt/skiff/coreenv/skiff-core-pinephone-neon
      squash: true
