name: CI

on:
  push:
    branches: [master, next, stable]

# Builds images for target boards.
jobs:
  device:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        skiffconf:
        - pi-0
        - pi-3,
        - pi-4
        - odroid-xu
        - odroid-u
        - odroid-c4
        - odroid-c2
        - apple-macbook
        - jetson-tx2
        # exceeds the storage limit
        # - jetson-nano,
        - pine64-phone
        - pine64-h64
    steps:
      - uses: actions/checkout@v2
      - name: Cache build cache and downloads
        uses: actions/cache@v2
        env:
          cache-name: cache-buildroot-device
        with:
          path: ~/br-cache/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.skiffconf }}
      - name: Install buildroot apt deps
        run: |
          sudo apt-get install -y libelf-dev
      - name: Print help and packages list
        run: |
          cd $GITHUB_WORKSPACE
          make help
      - name: Build the system image
        env:
          SKIFF_DEVICE_CONFIG: ${{ matrix.skiffconf }}
        run: |
          cd $GITHUB_WORKSPACE
          export TERM=xterm
          export BR2_CCACHE_DIR=${HOME}/br-cache/ccache
          export BR2_DL_DIR=${HOME}/br-cache/dl
          export SKIFF_WORKSPACE=docker
          SKIFF_TARGET=$(echo ${SKIFF_DEVICE_CONFIG} | sed "s#-#/#g")
          export SKIFF_CONFIG=${SKIFF_TARGET},skiff/core,core/nixos
          make -s configure compile check
          mkdir -p workflow-artifacts
          tar -cvf ./workflow-artifacts/images.tar.gz -C ./workspaces/$SKIFF_WORKSPACE/images/ ./
      - uses: actions/upload-artifact@v2
        with:	
          name: images-${{ matrix.skiffconf }}.tar.gz
          path: ${{ github.workspace }}/workflow-artifacts/images.tar.gz

