name: CI

on:
  push:
    branches: [master, next, stable]

# Builds images for target boards.
jobs:
  device:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        skiffconf:
        - apple-macbook
        - odroid-c4
        - odroid-u
        - odroid-xu
        - pi-0
        - pi-3
        - pi-4
        - pine64-book
        - pine64-phone
        - virt-wsl
        # exceeds the storage limit
        # - pine64-h64
        # - jetson-nano
        # - jetson-tx2
    steps:
      - uses: actions/checkout@v2
      - name: Cache build cache and downloads
        uses: actions/cache@v2
        env:
          cache-name: cache-buildroot-device
        with:
          path: ~/br-cache/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.skiffconf }}
      - name: Clear caches if necessary
        run: |
          # necessary to save space
          if [ ! -f ~/br-cache/ccache-v1 ]; then
            echo "Clearing old compiler cache..."
            rm -rf ~/br-cache/ccache* || true
            mkdir -p ~/br-cache/ccache
            touch ~/br-cache/ccache-v1
          fi
          if [ ! -f ~/br-cache/dl-v1 ]; then
            echo "Clearing old downloads cache..."
            rm -rf ~/br-cache/dl* || true
            mkdir -p ~/br-cache/dl
            touch ~/br-cache/dl-v1
          fi
      - name: Install buildroot apt deps
        run: |
          sudo apt-get install -y libelf-dev
      - name: Print help and packages list
        run: |
          cd $GITHUB_WORKSPACE
          make help
      - name: Build the system image
        env:
          SKIFF_DEVICE_CONFIG: ${{ matrix.skiffconf }}
        run: |
          cd $GITHUB_WORKSPACE
          export TERM=xterm
          export BR2_CCACHE_DIR=${HOME}/br-cache/ccache
          export BR2_DL_DIR=${HOME}/br-cache/dl
          export SKIFF_WORKSPACE=docker
          SKIFF_TARGET=$(echo ${SKIFF_DEVICE_CONFIG} | sed "s#-#/#g")
          export SKIFF_CONFIG=${SKIFF_TARGET},skiff/core,core/gentoo
          make -s configure compile check
          rm -rf ./workspaces/${SKIFF_WORKSPACE}/{build,extra_images,host,target,staging}
          mkdir -p workflow-artifacts
          tar -cvf ./workflow-artifacts/images.tar.gz --exclude="rootfs.cpio" -C ./workspaces/$SKIFF_WORKSPACE/images/ ./
      - uses: actions/upload-artifact@v2
        with:	
          name: images-${{ matrix.skiffconf }}.tar.gz
          path: ${{ github.workspace }}/workflow-artifacts/images.tar.gz


