name: Devices

on:
  push:
    branches: [master, next, stable]

# Builds images for target boards.
jobs:
  device:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 2880
    strategy:
      matrix:
        skiffconf:
        - apple-macbook
        - odroid-c4
        - odroid-xu
        - pi-0
        - pi-3
        - pi-4
        - pine64-book
        - pine64-phone
        - pine64-h64
        - jetson-tx2
        # temporarily disabled targets:
        # - jetson-nano
        # - odroid-u
        # - virt-wsl
    steps:
      - uses: actions/checkout@v4
      - name: Update the submodule
        run: |
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive

      - name: Cache build cache and downloads
        uses: actions/cache@v4
        env:
          cache-name: cache-buildroot
        with:
          path: ~/br-cache/
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Clear caches if necessary
        run: |
          # necessary to save space
          if [ ! -f ~/br-cache/ccache-v3 ]; then
            echo "Clearing old compiler cache..."
            rm -rf ~/br-cache/ccache* || true
            mkdir -p ~/br-cache/ccache
            touch ~/br-cache/ccache-v3
          fi
          if [ ! -f ~/br-cache/dl-v3 ]; then
            echo "Clearing old downloads cache..."
            rm -rf ~/br-cache/dl* || true
            mkdir -p ~/br-cache/dl
            touch ~/br-cache/dl-v3
          fi

      - name: Install buildroot apt deps
        run: |
          sudo apt-get install -y libelf-dev

      - name: Print help and packages list
        run: |
          cd $GITHUB_WORKSPACE
          make help

      - name: Enable using a pre-built toolchain
        run: |
          cd $GITHUB_WORKSPACE
          echo "BR2_TOOLCHAIN_EXTERNAL=y" > ./overrides/buildroot/toolchain

      - name: Build the system image
        env:
          SKIFF_DEVICE_CONFIG: ${{ matrix.skiffconf }}
        run: |
          cd $GITHUB_WORKSPACE
          export TERM=xterm
          export PATH=/usr/sbin:/usr/bin:/sbin:/bin
          export BR2_CCACHE_DIR=${HOME}/br-cache/ccache
          export BR2_DL_DIR=${HOME}/br-cache/dl
          echo "Cache dir: ${HOME}/br-cache"
          SKIFF_TARGET=$(echo ${SKIFF_DEVICE_CONFIG} | sed "s#-#/#g")
          export SKIFF_CONFIG=${SKIFF_TARGET},skiff/core,core/gentoo
          export SKIFF_WORKSPACE=${SKIFF_DEVICE_CONFIG}
          rm -rf ./workspaces/${SKIFF_WORKSPACE} || true
          make -s configure
          cd ./workspaces/${SKIFF_WORKSPACE}
          make -s host-python
          cd ../../
          make -s compile
          make -s check
          rm -rf ./workspaces/${SKIFF_WORKSPACE}/{build,extra_images,host,target,staging}
          mkdir -p workflow-artifacts
          tar -cvf ./workflow-artifacts/images.tar.gz --exclude="rootfs.cpio" -C ./workspaces/$SKIFF_WORKSPACE/images/ ./

      # Upload system image
      - uses: actions/upload-artifact@v4
        with:
          name: images-${{ matrix.skiffconf }}.tar.gz
          path: ${{ github.workspace }}/workflow-artifacts/images.tar.gz
